name: CI

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ "*" ]

jobs:
    test:
        name: "PHPUnit: MW ${{ matrix.mw }}, PHP ${{ matrix.php }}"

        runs-on: ubuntu-latest
        env:
            EXTENSION: 'PagePort'

        strategy:
            matrix:
                include:
                    - mw: 'REL1_35'
                      php: 7.4

        defaults:
            run:
                working-directory: mediawiki

        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: mbstring, intl
                  tools: composer:1

            -   name: Cache MediaWiki
                id: cache-mediawiki
                uses: actions/cache@v2
                with:
                    path: |
                        mediawiki
                        !mediawiki/extensions/
                        !mediawiki/vendor/
                    key: mw_${{ matrix.mw }}-php${{ matrix.php }}-${{ env.EXTENSION }}-v20

            -   name: Cache Composer cache
                uses: actions/cache@v2
                with:
                    path: ~/.composer/cache
                    key: composer-php${{ matrix.php }}-${{ env.EXTENSION }}

            - uses: actions/checkout@v2
              with:
                  path: Project

            - name: Install MediaWiki
              working-directory: ~
              run: bash Project/.github/workflows/install_mediawiki.sh ${{ matrix.mw }} ${{ env.EXTENSION }}

            - uses: actions/checkout@v2
              with:
                  path: mediawiki/extensions/${{ env.EXTENSION }}

            - name: Composer update
              run: composer update

            - name: Run PHPUnit
              run: php tests/phpunit/phpunit.php extensions/${{ env.EXTENSION }}/tests/phpunit
